### ISSUE TITLE
Typos in .tex, .rst versions

### ISSUE THREAD

**Issue by earthbound19** [karask/satoshi-paper#6]
Re my comment in https://github.com/karask/satoshi-paper/pull/5 :

There are paragraphs ending without periods in the .tex and .rst versions; my patch fixed typos in the .md version.

Question: what master document did this error (apparently) propogate from in the .md, .tex and .rst versions? Or how did this error show up in all three of them? Could a master document be fixed up and converted to these other three formats to fix this?

**Comment by karask** [comment]
Hi @earthbound19 

Five years later... there is no master document. It was probably propagated by copy/paste..? Don't even remember :-)

You've sent a PR to fix the above so after that the issue was kind of forgotten :-D

Thanks
